### ISSUE TITLE
Regarding the development progress of Upscore

### ISSUE THREAD

**Issue by koktingfeng** [EQuimper/MyOwnChallenge-SuperHeroesTwitterBotCoding#1]
@EQuimper @SOSANA @mannyhenri  PLEASE give us an update

**Comment by koktingfeng** [comment]
Hello can I get any feedback at all??

**Comment by EQuimper** [comment]
First this is not the place to talk about a project who I don't even know if I work on it. This is a personnal repos and this is not your place. Email manny if you need help with this case.

**Comment by koktingfeng** [comment]
@EQuimper I would like to know whether Manny instruct you guys to tell us that the website is more than 90% completed when it was obviously not? Just so that he could collect payment?

**Comment by EQuimper** [comment]
I don't have any info about this. I'm just a contractor and I don't know what happen with this project. Cause if I know I would work on it right now. Sorry email him is the only solution. Gonna email him for you.
